openapi: 3.1.0
info:
  title: Sheet to GPT API
  description: Access and retrieve data from Google Sheets
  version: 1.0.0
servers:
  - url: https://sheet-to-gpt.onrender.com
  - url: http://localhost:3000
paths:
  /api/get-data:
    get:
      summary: Retrieve data from the Data sheet
      operationId: getData
      responses:
        '200':
          description: Data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        Date:
                          type: string
                          example: "02/20/2023"
                        Day:
                          type: string
                          example: "Monday"
                        Category:
                          type: string
                          example: "Inbox Management"
                        Tasks Completed:
                          type: string
                          example: "Cleaned inbox, labeled emails, replied to recruitment messages."
                    description: Array of row objects with column headers as keys
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                        example: 84
                      page:
                        type: integer
                        example: 1
                      limit:
                        type: integer
                        example: 10
                      totalPages:
                        type: integer
                        example: 9
        '404':
          description: No data found in the sheet
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Failed to retrieve data'
                  details:
                    type: string
                    example: 'No data found'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Failed to retrieve data'
                  details:
                    type: string
                    example: 'Error details...'

  /api/get-email:
    get:
      summary: Retrieve data from the Email sheet with pagination and filtering
      operationId: getEmail
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for pagination
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
          description: Number of items per page
        - name: subject
          in: query
          schema:
            type: string
          description: Filter emails by subject (case-insensitive partial match)
        - name: date
          in: query
          schema:
            type: string
          description: Filter emails by date (case-insensitive partial match)
        - name: sender
          in: query
          schema:
            type: string
          description: Filter emails by sender name (case-insensitive partial match)
        - name: status
          in: query
          schema:
            type: string
          description: Filter emails by status (case-insensitive partial match)
      responses:
        '200':
          description: Email data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        Email ID:
                          type: string
                          example: "#msg-f:1827228799333968327"
                        Subject:
                          type: string
                          example: ""
                        Date:
                          type: string
                          example: "Mar 21, 2025, 11:19 AM"
                        Email Link:
                          type: string
                          example: "https://mail.google.com/mail/u/0/#search/helpdesk/FMfcgzQZTpsQMsVJdbRNDrtqXPMmWQbZ"
                        Status:
                          type: string
                          example: "saved"
                        Time Stamo:
                          type: string
                          example: ""
                        Content:
                          type: string
                          example: "Email content..."
                    description: Array of row objects with column headers as keys
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                        example: 9
                      page:
                        type: integer
                        example: 1
                      limit:
                        type: integer
                        example: 10
                      totalPages:
                        type: integer
                        example: 1
        '404':
          description: No data found in the sheet
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Failed to retrieve email data'
                  details:
                    type: string
                    example: 'No data found'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Failed to retrieve email data'
                  details:
                    type: string
                    example: 'Error details...'

  /api/get-slack-messages:
    get:
      summary: Retrieve data from the Slack Messages sheet
      operationId: getSlackMessages
      responses:
        '200':
          description: Slack messages data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        slack_msg_1742986234538_scouf6:
                          type: string
                          example: "slack_msg_1742986238071_g05n95"
                        https://jim-gup5582.slack.com/archives/C08EUAB57MF/p1742302130158559:
                          type: string
                          example: "https://jim-gup5582.slack.com/archives/C08EUAB57MF/p1742302207368349"
                        Mar 26, 2025:
                          type: string
                          example: "Mar 26, 2025"
                        "5:48 AM":
                          type: string
                          example: "5:50"
                        Jim:
                          type: string
                          example: "Jim"
                        "AI Dev Tools Night, April 2, Salesforce Tower":
                          type: string
                          example: "test"
                        Added:
                          type: string
                          example: "Added"
                        "2025-03-26T10:50:36.581Z":
                          type: string
                          example: "2025-03-26T10:50:39.060Z"
                    description: Array of row objects with column headers as keys
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                        example: 3
                      page:
                        type: integer
                        example: 1
                      limit:
                        type: integer
                        example: 10
                      totalPages:
                        type: integer
                        example: 1
        '404':
          description: No data found in the sheet
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Failed to retrieve slack messages data'
                  details:
                    type: string
                    example: 'No data found'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Failed to retrieve slack messages data'
                  details:
                    type: string
                    example: 'Error details...'

  /health:
    get:
      summary: Health check endpoint
      operationId: healthCheck
      responses:
        '200':
          description: API is healthy
          content:
            text/plain:
              schema:
                type: string
                example: 'OK' 