services:
  - type: web
    name: sheet-to-gpt
    env: node
    buildCommand: npm install
    startCommand: export NODE_OPTIONS=--openssl-legacy-provider && node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: DEFAULT_SPREADSHEET_ID
        value: 1m6e-HTb1W_trKMKgkkM-ItcuwJJW-Ab6lM_TKmOAee4
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false 